### ISSUE TITLE
Precomputed flows for DAVIS 2016?

### ISSUE THREAD

**Issue by edizhuang** [charigyang/motiongrouping#10]
Hi,

I'm interested in your work but have some issues to run the code.

So should precomputed flows be generated for DAVIS 2016? In raft, when I run the code of run_inference.py, it only generates some empty folders inside DAVIS folder (for raft I have followed the requirement instruction via conda). 

Could you check run_inference.py and predict.py to see why?

Thanks,

**Comment by charigyang** [comment]
Hi, thanks for interest in our work.

Mine works fine.  I suspect it might be directory?

Make sure your path structure is something like
/path/to/DAVIS2016/JPEGImages to where it contains the images
and you use
data_path = "/path/to/DAVIS2016" in line 4 of run_inference.py

Let me know if it doesn't work and I'll debug further.

**Comment by edizhuang** [comment]
Hi,

I think I've fixed it. Just add '/480p' or '/1080p' following '/JPEGImages' at line 7 of run_inference.py.

Thanks,
