### ISSUE TITLE
About the initalization on the slot embedding.

### ISSUE THREAD

**Issue by Mark12Ding** [charigyang/motiongrouping#16]
Thanks for sharing the code. I wonder about the performance using random initialization instead of learnable embedding. Since I found the code from L133 to L116 in model.py is commented out, does that mean the random initialization is inferior?
https://github.com/charigyang/motiongrouping/blob/e7d955e1bffe9fc973b38f076758fbb8d596e851/src/model.py#L113

**Comment by charigyang** [comment]
In the early expreiments we tried random slots that but it did not stably converge, not sure if it does now, but we just stick to learnable embeddings.

**Comment by Mark12Ding** [comment]
Yes, the same situation... Thanks for the reply!
