### ISSUE TITLE
How to use this to inference my own video and generate mask results?

### ISSUE THREAD

**Issue by LuoWeihao95** [charigyang/motiongrouping#3]
1. How could I input my own video to use your model?
2. When I use python eval.py --dataset MoCA  --flow_to_rgb --inference --resume_path {},  it seems that eval.py dosen't have the parameter '--inference'. 
3. I delete '--inference' and run eval.py. It just generated acc value without mask results. How to generate mask results?

Could you help to solve these questions? Many thanks!

**Comment by charigyang** [comment]
Thanks for your intersest in our work.

1. See the "How to use this on your own data" section in the markdown. If any part is unclear please let me know and I'll answer and add more info.
2. Apologies, is a typo. just ignore the inference flag.
3. Lines 42-51 in eval.py should be saving the masks. Please check the paths indicated -- if problem still persists please let me know and I'll try to fix this.

**Comment by LuoWeihao95** [comment]
> Thanks for your intersest in our work.
> 
> 1. See the "How to use this on your own data" section in the markdown. If any part is unclear please let me know and I'll answer and add more info.
> 2. Apologies, is a typo. just ignore the inference flag. I will update this in the next iteration.
> 3. Lines 42-51 in eval.py should be saving the masks. Please check the paths indicated -- if problem still persists please let me know and I'll try to fix this.

Thanks for your reply. It is really helpful. But I still meet a problem.
If I just want to inference my video without gt, how to fill 'gt_dir' in config.py?

**Comment by charigyang** [comment]
You can just comment out all the lines that uses 'gt_dir' (including those to calculate accuracy, etc), as they won't be relevant to you.
